import React, { useMemo } from 'react';
import { MarkdownMath } from './MarkdownMath';
import { normalizeMathMarkdown } from '../../lib/aiContent/normalizeMathMarkdown';

interface Props {
  children: string;
  className?: string;
  discreet?: boolean;
  /** 'full' for complete math rendering, 'preview' for simplified view in cards */
  mode?: 'full' | 'preview';
}

/**
 * RichText - A thin wrapper over MarkdownMath that handles normalization.
 * 
 * It is the preferred component for mixed prose/markdown/math content
 * generated by AI models.
 */
function RichTextInner({ children, className, discreet = false, mode = 'full' }: Props) {
  const normalized = useMemo(() => {
    if (!children) return '';
    return normalizeMathMarkdown(children);
  }, [children]);

  if (!normalized) return null;
  
  return (
    <MarkdownMath 
      content={normalized} 
      className={className} 
      discreet={discreet}
      mode={mode}
    />
  );
}

export const RichText = React.memo(RichTextInner);
export default RichText;
